[package]
name = "hello_world"
version = "0.1.0"
authors = ["marut.singh <marut.singh@broctagon.com>"]

[dependencies]
bytes = "0.4"
tokio-service = "0.1"
futures = "0.1"
tokio-io = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"

